### PR TITLE
Features branch

### PR DESCRIPTION
**Pull request by rida-elbahtouri**
<h1>Building with Backgrounds and Gradients</h1>

#### What does this PR do?
created an apple website clone

### in this project I :

- created a new HTML document.

- Think about all the elements on the page and how they are grouped together.

- Layout the basic structure of the page using empty semantic HTML elements that are appropriately sized and positioned. 

- Set up the top navigation bar. same as that gradient achieved

- used CSS grid to organize my main section

#### How should this be manually tested?
just clone the project and open the index.html file

### CODE REVIEW

**Comment by rida-elbahtouri** [comment]
<h1>Building with Backgrounds and Gradients</h1>

### in this project I :

- created a new HTML document.

- Think about all the elements on the page and how they are grouped together.

- Layout the basic structure of the page using empty semantic HTML elements that are appropriately sized and positioned. 

- Set up the top navigation bar. same as that gradient achieved

- used CSS grid to organize my main section

**Comment by santiago-dev96** [comment]
# Pull Request under review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Invalid PR :no_entry_sign:
This PR is invalid because of the following reasons.
1. The PR title is not descriptive
2. The PR summary is not descriptive

I noticed that you outlined the changes introduced in a comment, but I have to make sure that you are following the professional standards, so I can't allow that because that is definitely not a good practice.

Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there). This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

Please submit another CRR (Code Review Request) after implementing the required changes.

You can find me in slack as **srodrig**. Have a nice day :wave:!

**Comment by rammazzoti2000** [comment]
### Hello @rida-elbahtouri :wave: 
As mentioned by the previous TSE this pull request was marked as invalid for the reasons mentioned above, and for that this pull request must be closed.
To make another code review request, open a new pulll request and make sure this time it looks professional (as suggested by the previous TSE)
#### 
For more clarifications you can find me on slack as `alexandru`. Happy coding :wave:

**Pull request closed without merging**
